# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://github.com/daniloromero/daniloromero.github.io"
languageCode = "en"
defaultContentLanguage = "en"

title = "Danilo"
# copyright = "Copy, _right?_ :thinking_face:"
theme = "congo"
enableEmoji = true
enableRobotsTXT = true

summaryLength = 0

[author]
  name = "Danilo Romero"
  image = "author.jpg"
  links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
 
    { github = "https://github.com/daniloromero" },
    { linkedin = "https://www.linkedin.com/in/danilo-romero-beltran/" },
  
    { twitter = "https://twitter.com/terpenoide" },
  #   { youtube = "https://youtube.com/username" },
  ]
